# Hologram config

# The directory containing the source files to parse
source: ../assets/scss

# The directory that hologram will build to
destination: ./docs

# The assets needed to build the docs (includes header.html, footer.html, etc)
# documentation_assets: ./templates

# Hologram theme
documentation_assets: ./cortana
custom_markdown: ./cortana/CortanaMarkdownRenderer.rb

# To have a custom index page build with your README.md
index: README

# List all css to include for the styleguide render examples (path from styleguide directory)
#css_include:
#  - './assets/css/vendors.css'
#  - './assets/css/styles.css'

# List all js to include for the styleguide render examples (path from styleguide directory)
js_include:
  - 'http://code.jquery.com/jquery-1.10.2.min.js'
#  - './theme-build/js/main.min.js'
#  - './theme-build/js/vendors.min.js'

# String who is used to split the category name and create category wrapper
name_scope: ' - '

# This is a custom markdown renderer (see Redcarpet documentation for
# how to do this)
# custom_markdown: trulia_markdown_renderer.rb
